### ISSUE TITLE
Filtro de notícias está captando muitos links que não são *protestos*

### ISSUE THREAD

**Issue by GiulianoBrizolla** [Jhouny/Sistema-MAPCON#4]
Dentro da aba "notícias rastreadas" encontram-se mais notícias relacionadas a temas diversos do que protestos. Temas que foram captados com mais frequência: Debates e campanhas políticas, paradas por conta de obras, eventos (musicais, teatrais, esportivos, etc) 

OBS: acredito que a maior parte seja pela palavra-chave: bloqueio ou algo relacionado

**Comment by Jhouny** [comment]
Correção será feita no desenvolvimento de #5 com NLP.
